name: Blogger Auto Post

on:
  schedule:
    - cron: "0 6 * * *"   # every day at 06:00 UTC
  workflow_dispatch:       # manual trigger

permissions:
  contents: write   # needed to push changes

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automation-data branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: automation-data   # <-- start directly on automation-data

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run Blogger script
        env:
          BLOGGER_SECRET_MAIL: ${{ secrets.BLOGGER_SECRET_MAIL }}
          GMAIL_USER:          ${{ secrets.GMAIL_USER }}
          GMAIL_PASS:          ${{ secrets.GMAIL_PASS }}
          GEMINI_API_KEY:      ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py

      - name: Commit history update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .data/blog_history.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update blog history [skip ci]"
            git pull --rebase --strategy-option=ours origin automation-data || true
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:automation-data
          fi
