name: Daily Trend Mail with Playwright

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Run bot
        run: python main.py
        env:
          BLOGGER_SECRET_MAIL: ${{ secrets.BLOGGER_SECRET_MAIL }}
          GMAIL_USER:          ${{ secrets.GMAIL_USER }}
          GMAIL_PASS:          ${{ secrets.GMAIL_PASS }}
          GEMINI_API_KEY:      ${{ secrets.GEMINI_API_KEY }}
